global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'iot_ids_server'
    static_configs:
      - targets: ['localhost:8000']
  - job_name: 'iot_ids_client1'
    static_configs:
      - targets: ['localhost:8001']
  - job_name: 'iot_ids_client2'
    static_configs:
      - targets: ['localhost:8002']
  - job_name: 'iot_ids_client3'
    static_configs:
      - targets: ['localhost:8003']